Repository sendgrid/dx-mobile, pull requests merged in 2018-10, with the labels that each got.

#12 EID-977 add multiple repos
  ios/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
  lib/github/graphql.dart
  lib/github/graphql_offline.dart
  lib/github/parsers.dart
  lib/github/repository.dart
  lib/main.dart
  lib/pages/dashboard.dart
  lib/pages/issuetimelineview.dart
  lib/pages/repolist.dart
Labels: difficulty: hard, hacktoberfest, status: code review request, type: sendgrid enhancement

#16 Make dx-mobile work with the latest version of flutter
  lib/github/graphql.dart
  lib/pages/issuetimelineview.dart
  pubspec.yaml
Labels: difficulty: medium, enhancement, hacktoberfest, status: cla not signed, status: hacktoberfest approved, type: sendgrid enhancement

#20 Readme Update for Flutter new version
  README.md
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: docs update

#23 Improve Dashboard & Timeline UI
  lib/common/timeline_widgets.dart
  lib/pages/dashboard.dart
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: sendgrid enhancement

#14 Adding first timers file
  FIRST_TIMERS.md
Labels: difficulty: medium, good first issue, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: docs update

#24 Add loading state to dashboard #patch
  lib/pages/dashboard.dart
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: sendgrid enhancement

#27 #Minor Fix Link to LICENSE in README.md
  README.md
Labels: difficulty: easy, status: code review request, type: docs update

#13 Add EditorConfig
  .editorconfig
Labels: difficulty: easy, enhancement, hacktoberfest, status: hacktoberfest approved
